version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: golang_container
    tty: true
    volumes:
      - ./src:/go/src
    working_dir: /go/src
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
